jenkins:
  systemMessage: "You are on the Jenkins meant to run Team2's CI/CD pipelines. Please contact team2@pragra.com for additional access or issues."
tool:
  git:
    installations:
    - home: "/usr/bin/git"
      name: "git"
    - home: "/bin/git"
      name: "git-new"
    - home: "/opt/git"
      name: "git-portable"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  powerShellInstallation:
    installations:
    - home: "powershell.exe"
      name: "DefaultWindows"
    - home: "pwsh"
      name: "DefaultLinux"
